# Generated by Django 4.0.5 on 2022-08-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0002_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='listo',
            new_name='completada',
        ),
    ]
