# Generated by Django 4.0.5 on 2022-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengeApp', '0004_rename_titulo_tarea_texto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['completada']},
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
